name: Auto-Download ERA5 to Google Drive

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the top of the hour (e.g., 1:00, 2:00)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Install System Rules
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R Packages
        run: |
          Rscript -e 'install.packages(c("ecmwfr", "googledrive"), repos="https://cloud.r-project.org/")'

      - name: Run Script
        env:
          CDS_API_KEY: ${{ secrets.CDS_API_KEY }}
        run: Rscript download_era5.R
